name: Devopsdemo

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy
        run: |
          echo "Deploy started..."

          mkdir -p /home/ubuntu/Devopsdemo
          rsync -av --exclude '.git' ./ /home/ubuntu/Devopsdemo/

          cd /home/ubuntu/Devopsdemo

          npm install

          pm2 delete app || true
          pm2 start app.js --name app

          pm2 save
